"""исправление ошибки с уникальностью id пользователся в cards

Revision ID: 0252ddcb9d43
Revises: d2af68f8af30
Create Date: 2025-05-06 14:18:39.343554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0252ddcb9d43'
down_revision: Union[str, None] = 'd2af68f8af30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
